apiVersion: v1
kind: Service
metadata:
  namespace: lagom-services
  name: telegram-bot-service
  labels:
    app: telegram-bot
    role: service
    tier: backend
spec:
  ports:
  - name: bot
    port: 9000
    targetPort: 9000
  selector:
    app: telegram-bot
    role: service
    tier: backend  
  type: NodePort