apiVersion: v1
kind: Service
metadata: 
  name: helloworld-service
  namespace: lagom-services
#  namespace: telegram-bot
  labels: 
    app: test-service
    role: service
    tier: backend  
spec:
  ports: 
  - name: bot
    port: 9000
    targetPort: 9000
    nodePort: 30004
    protocol: TCP
  selector:
    app: helloworld-service
    role: service
    tier: backend  
  type: NodePort